create table users(
      userid varchar(50) not null primary key,
      username varchar(50) ,
      password varchar(50) not null,
      city varchar(50),
      enabled boolean not null);

create table authorities (
      userid varchar(50) not null,
      authority varchar(50) not null,
      constraint fk_authorities_users foreign key(userid) references users(userid));
      create unique index ix_auth_username on authorities (userid,authority);

--User Information
insert into users values('admin','SuperVisor','admin','Kaohsiung',TRUE);
insert into users values('user','Common User','user','Taipei',TRUE);
insert into authorities values('user','ROLE_USER');
insert into authorities values('admin','ROLE_USER');
insert into authorities values('admin','ROLE_ADMIN');

create table groups (
  id bigint generated by default as identity(start with 0) primary key,
  group_name varchar(50) not null);

create table group_authorities (
  group_id bigint not null,
  authority varchar(50) not null,
  constraint fk_group_authorities_group foreign key(group_id) references groups(id));

create table group_members (
  id bigint generated by default as identity(start with 0) primary key,
  userid varchar(50) not null,
  group_id bigint not null,
  constraint fk_group_members_group foreign key(group_id) references groups(id));

create table persistent_logins (
  userid varchar(64) not null,
  series varchar(64) primary key,
  token varchar(64) not null,
  last_used timestamp not null);
